# ==========================================
# Browser (mandatory for youtube)
# ==========================================

# try to use cookies from browser to bypass anti-bot detection systems of youtube. (working as of July 2026. May not work in the future)
# edit your preferred browser in. I used firefox.

--cookies-from-browser firefox

# this is optional and you only need it if you have Node.js installed.

--js-runtimes node

# ==========================================
# Download
# ==========================================

# define format and criteria of downloads
# the best audio available on the uploaded file. Saved it as m4a.
# this is the easiest thing to tweak. If you want to use mp3 for best compatibility with old devices just change the format below.

--format bestaudio
--extract-audio
--audio-format m4a

--continue
--no-overwrites

# ==========================================
# Metadata
# ==========================================

# copy the position in the youtube playlist in the metadata track to enumerate them as they are uploaded.

--parse-metadata "playlist_index:%(track_number)s"

# removes the strings listed from the titles if they are part of the name of the uploaded file. (?i) case-insensitive match

--replace-in-metadata title "(?i)\s*[\(\[]Official Music Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Lyric Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Lyrics Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Audio[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Lyric Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Lyrics[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Visualizer[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Visualiser[\)\]]" ""

# acquires the rest of the available metadata (usually youtube provides only track, artist, album).
# we still want to use the thumbnail as a temporary cover for all the tracks we download. The quality will not be great.

--add-metadata
--embed-thumbnail
--convert-thumbnail jpg

# this checks for windows compatibility for the filename.

--windows-filenames

# ==========================================
# Output
# ==========================================

# defines the general output of the file.

-o "%(artist,uploader)s/%(album,playlist_title)s/%(track_number,playlist_index)02d - %(title)s.%(ext)s"