# ==========================================
# Browser & Client
# ==========================================

--cookies-from-browser firefox
--js-runtimes node

--extractor-args "youtube:player-client=web_embedded,tv,web"

# ==========================================
# Download (Opus)
# ==========================================

--format "bestaudio/best"
--extract-audio
--audio-format opus
--format-sort "abr"

--continue

# ==========================================
# Cover Album, high compatibility with different devices
# ==========================================

--embed-thumbnail
--write-thumbnail
--convert-thumbnails jpg

# Crop squared 1:1 and conversion to yuv420p
--ppa "ThumbnailsConvertor+ffmpeg:-vf crop=ih:ih,format=yuv420p"

# ==========================================
# Metadata
# ==========================================

# 1. Cleaning "- Topic" from the channell name
--replace-in-metadata uploader "(?i)\s*-\s*Topic$" ""

# 2. If artist tag is empty, fill it with "uploader"
--parse-metadata "%(artist)s|%(uploader)s:^(?:NA|None|)\s*\|(?P<artist>.+)$"

# 3. Assign playlist index to track index
--parse-metadata "%(playlist_index)s:%(track_number)s"

# 4. Copy playlist title to album tag
--parse-metadata "%(playlist_title)s:%(album)s"

# 5. Removes prefixes such as: ("Album - ", "EP - ", "Single - ")
--replace-in-metadata album "(?i)^(?:Album|EP|Single)\s*-\s*" ""
--replace-in-metadata playlist_title "(?i)^(?:Album|EP|Single)\s*-\s*" ""

# 6. Separate artist name from titles (usefull in some cases when " - " is present in the title of the song)
--parse-metadata "%(artist)s|%(title)s:^\s*\|(?P<artist>.+?)\s+-\s+(?P<title>.+)$"

# 7. Force the primary artist to be the only one in the tag (removes feat., commas, etc.)
--replace-in-metadata artist "(?i)\s*(?:,|\s+&\s+|\s+x\s+|\s+feat\.\s+|\s+ft\.\s+).*" ""

# Clean some superfluous wording
--replace-in-metadata title "(?i)\s*[\(\[]Official Music Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Lyric Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Lyrics Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Official Audio[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Lyric Video[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Lyrics[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Visualizer[\)\]]" ""
--replace-in-metadata title "(?i)\s*[\(\[]Visualiser[\)\]]" ""

--add-metadata
--windows-filenames

# ==========================================
# Output, Folder Structure, Tracks and Cover
# ==========================================

-o "Libreria/%(artist,uploader)s/%(album,playlist_title)s/%(track_number,playlist_index)02d - %(title)s.%(ext)s"
-o "thumbnail:Libreria/%(artist,uploader)s/%(album,playlist_title)s/cover.%(ext)s"
